services:
  autoparts-app:
    build: .
    image: autoparts-app
    container_name: autoparts-app
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:${HOST_PORT:-8081}:${PORT:-80}"
    environment:
      NODE_ENV: production
      PORT: ${PORT:-80}
    restart: unless-stopped
