import dotenv from "dotenv";

dotenv.config();

const OWNER_NUMBER = process.env.OWNER_NUMBER || "";

const SELLER_NUMBERS = (process.env.SELLER_NUMBERS || "")
  .split(",")
  .map((value) => value.trim())
  .filter(Boolean);

const META_WHATSAPP_TOKEN = process.env.META_WHATSAPP_TOKEN || "";
const META_PHONE_NUMBER_ID = process.env.META_PHONE_NUMBER_ID || "";
const META_WEBHOOK_VERIFICATION_TOKEN =
  process.env.META_WEBHOOK_VERIFICATION_TOKEN || "";
const META_TEMPLATE_SELLER_INQUIRY =
  process.env.META_TEMPLATE_SELLER_INQUIRY || "";
const META_TEMPLATE_SELLER_INQUIRY_FLOW_TITLE =
  process.env.META_TEMPLATE_SELLER_INQUIRY_FLOW_TITLE || "";
const META_TEMPLATE_LANGUAGE = process.env.META_TEMPLATE_LANGUAGE || "sr";
const META_TEMPLATE_BUYER_OFFER = process.env.META_TEMPLATE_BUYER_OFFER || "";
const META_TEMPLATE_BUYER_OFFER_FLOW_TITLE =
  process.env.META_TEMPLATE_BUYER_OFFER_FLOW_TITLE || "";
const META_TEMPLATE_OWNER_NOTIFICATION =
  process.env.META_TEMPLATE_OWNER_NOTIFICATION || "";

  const BID_ID_START = Number.isFinite(Number(process.env.BID_ID_START))
    ? Number(process.env.BID_ID_START)
    : 10001;

const BID_STORE_TTL_MS = Number.isFinite(Number(process.env.BID_STORE_TTL_HOURS))
  ? Number(process.env.BID_STORE_TTL_HOURS) * 60 * 60 * 1000
  : 72 * 60 * 60 * 1000;

export const ENV = {
  OWNER_NUMBER,
  SELLER_NUMBERS,
  META_WHATSAPP_TOKEN,
  META_PHONE_NUMBER_ID,
  META_WEBHOOK_VERIFICATION_TOKEN,
  META_TEMPLATE_SELLER_INQUIRY,
  META_TEMPLATE_SELLER_INQUIRY_FLOW_TITLE,
  META_TEMPLATE_LANGUAGE,
  META_TEMPLATE_BUYER_OFFER,
  META_TEMPLATE_BUYER_OFFER_FLOW_TITLE,
  META_TEMPLATE_OWNER_NOTIFICATION,
  BID_ID_START,
  BID_STORE_TTL_MS,
};
